openapi: 3.0.3
info:
  title: Farmstall API
  version: v1
servers:
- url: https://farmstall.designapis.com/v1
paths: 
  /reviews:
    get:
      description: Get reviews
      parameters:
      - name: maxRating
        description: Filter by a rating ceiling
        in: query
        schema:
          type: number
      responses:
        200:
          description: reviews returned
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                      pattern: '^[0-9a-fA-F\-]{36}$'
                    message:
                      type: string
                    rating:
                      type: integer
                      minimum: 1
                      maximum: 5
                    userId:
                      type: string
                      pattern: '^[0-9a-fA-F\-]{36}$'
                      nullable: true
    post:
      description: Post a review
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: A great time was had by all
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  example: 5
      responses:
        '201':
          description: Successful creation of a new review
          content:
            application/json:
              schema:
                type: object
                properties: 
                  message:
                    type: string
                    example: A great time was had by all
                  rating:
                    type: integer
                    minimum: 1
                    maximum: 5
                    example: 5
                  userId:
                    type: string
                    nullable: true
                    pattern: '[a-zA-Z-,0-9]{36}'
                    example: f7f680a8-d111-421f-b6b3-493ebf905078
                  uuid:
                    type: string
                    pattern: '[a-zA-Z-,0-9]{36}'
                    example: f7f680a8-d111-421f-b6b3-493ebf905078
  /reviews/{reviewId}:
    get:
      description: Get a single review by id
      parameters:
      - name: reviewId
        in: path
        required: true
        schema:
          type: string
          minLength: 36
          maxLength: 36
          pattern: '[a-zA-Z0-9-]+'
          example: 469240a9-8ef9-4a48-ae6e-65d29a01a9d0
      responses:
        '200':
          description: A single review
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: A great time was had by all
                  rating:
                    type: integer
                    minimum: 1
                    maximum: 5
                    example: 5
                  userId:
                    minLength: 36
                    maxLength: 36
                    pattern: '^[a-zA-Z0-9-]+$'
                    example: 469240a9-8ef9-4a48-ae6e-65d29a01a9d0
                  uuid:
                    minLength: 36
                    maxLength: 36
                    pattern: '^[a-zA-Z0-9-]+$'
                    example: 469240a9-8ef9-4a48-ae6e-65d29a01a9d0
  /users:
    post:
      description: Create a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: daywalker
                  minLength: 5
                password:
                  type: string
                  format: password
                  example: Wanderlust!1999
                fullname:
                  type: string
                  example: John Wick
      responses:
        '201':
          description: Successful creation of a user
          content:
            application/json:
            schema:
              type: object
              properties:
                username: 
                  type: string
                  example: daywalker
                fullname:
                  type: string
                  example: John Wick
                uuid:
                  type: string
                  pattern: '[a-zA-Z-,0-9]{36}'
                  example: f7f680a8-d111-421f-b6b3-493ebf905078
  /tokens:
    post:
      description: Create a token
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                username: 
                  type: string
                  example: daywalker
                password:
                  type: string
                  format: password
                  example: Wanderlust!1999
      responses:
        '201':
          description: Succesful creation of a token
          content:
            application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
